### PR TITLE
Updated test to support domain_name on ios_xr

### PR DESCRIPTION
**Pull request by jonnytpuppet**

### CODE REVIEW

**Comment by glennmatthews** [comment]
Please fix Rubocop failures:

```
tests/beaker_tests/netdev_stdlib/domain_name_provider_defaults.rb:64:19: C: Align the elements of an array literal if they span more than one line.
                  'no vrf context test']
                  ^^^^^^^^^^^^^^^^^^^^^

tests/beaker_tests/netdev_stdlib/domain_name_provider_defaults.rb:68:19: C: Align the elements of an array literal if they span more than one line.
                  'no vrf context test']
                  ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by glennmatthews** [comment]
Other than Rubocop failure, :+1:

**Comment by jonnytpuppet** [comment]
@glennmatthews code updated to fix rubocop failure, is this mergeable now please? Thanks

**Comment by robert-w-gries** [comment]
:+1:

**Pull request merged**
