### PR TITLE
search_domain, tests platform agnostic

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
@chburket @mikewiebe Need another review, i removed the un-needed cli based checks. makes the tests more platform independent whilst ensuring integrity.

**Comment by tphoney** [comment]
tests/beaker_tests/search_domain/search_domain_provider_defaults.rb passed in 175.03 seconds
      Test Suite: tests @ 2016-06-06 22:57:41 +0100

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 175.03 seconds
      Average Test Time: 175.03 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -

Failed Tests Cases:
Errored Tests Cases:
Skipped Tests Cases:
Pending Tests Cases:

No tests to run for suite 'post_suite'

**Comment by chburket** [comment]
:+1:

**Comment by tphoney** [comment]
@mikewiebe can i get a merge ? Charles is on board

**Comment by tphoney** [comment]
@chburket @mikewiebe on the nexus 
TestCase :: DOMAIN_NAME Resource :: All Attributes Defaults :: End
Begin teardown
End teardown
tests/beaker_tests/search_domain/search_domain_provider_defaults.rb passed in 39.23 seconds
      Test Suite: tests @ 2016-06-08 15:15:36 +0100

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 39.23 seconds
      Average Test Time: 39.23 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -

Failed Tests Cases:
Errored Tests Cases:
Skipped Tests Cases:
Pending Tests Cases:

No tests to run for suite 'post_suite'
No tests to run for suite 'pre_cleanup'
Cleanup: cleaning up after successful run
Warning: ssh connection to master has been terminated
Warning: ssh connection to n9kv1 has been terminated

**Pull request merged**
