### PR TITLE
add med missing-worst-as to bgp

### PR DESCRIPTION
**Pull request by andy91315**
1. Unable to make the beaker test 
( agent-lab4-nx env not correct)

### CODE REVIEW

**Comment by chrisvanheuveln** [comment]
You have 'username admin shelltype bash' in your config. Please change it to 'username admin shelltype vsh' to get it back on track.

**Comment by mikewiebe** [comment]
@andy91315 Please add beaker test and demo results and then we can merge.

**Comment by andy91315** [comment]
Beaker completed successfully, thanks.

confirm pass default non-default and title pattern beaker test

**Comment by chrisvanheuveln** [comment]
:+1

**Pull request merged**
