### PR TITLE
(NETDEV-39) add facility to syslog_server

### PR DESCRIPTION
**Pull request by shermdog**
Customer request.  Requires release of netdev_stdlib and merging of cisco/cisco-network-node-utils#583

### CODE REVIEW

**Comment by mikewiebe** [comment]
@shermdog I kicked off Travis again and it now passes.  I am also running these diffs against a few of our testbeds/images.  So far results are good.

**Comment by mikewiebe** [comment]
@shermdog The `cisco_node_utils` testing looks good.  When I attempted to test puppet though I got.

```
[mNotice: Downloading from https://forgeapi.puppetlabs.com ...[0m
[1;31mError: Could not install module 'puppetlabs-netdev_stdlib' (???)
  No version of 'puppetlabs-netdev_stdlib' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module[0m
universalprompt>echo "lastCmdStatus($?)"
```

I see that the version you are referencing the the `metadata.json` file is not yet released. We should hold on merging this PR until then.

**Comment by shermdog** [comment]
@mikewiebe yup - the changes are merged into netdev_stdlib, but not yet released. 

The PR for node_utils can be merged though if everything looks good.

**Comment by mikewiebe** [comment]
@shermdog Sounds good.  I just merged the PR for node_utils.

**Comment by shermdog** [comment]
@mikewiebe This is ready for merge.

**Comment by mikewiebe** [comment]
👍

**Pull request merged**
