### PR TITLE
add three properties to cisco_bgp

### PR DESCRIPTION
**Pull request by andy91315**
1. pass the beaker test

2. pass static analysis

### CODE REVIEW

**Comment by chrisvanheuveln** [comment]
Code looks fine but I'll hold off merging since I think you want to add `neighbor_down` to this commit.

**Comment by andy91315** [comment]
I have added the neighbor_down to it. because it is implement on node util I thought its code exists on the puppet side.

**Comment by chrisvanheuveln** [comment]
Thanks for adding that. Please see my comment on the NU side to rename this to `neighbor_down_fib_accelerate`

**Comment by chrisvanheuveln** [comment]
This looks good for merge but I see you added a couple more properties to your NU commit (suppress-inactive, distance, default-metric, etc). Are you going to add those to this PR as well? Either way this PR still needs to wait for the NU commit.

**Comment by chrisvanheuveln** [comment]
NU code has been merged. What's the status on this one and #89 ? This one looks ready to merge but it doesn't have all the attributes you added to NU. And #89 looks like it still needs some work.

**Comment by andy91315** [comment]
This one are properties for bgp and ready for merge. For #89 I still need some test and add the inject map.

**Pull request merged**
