### PR TITLE
Beaker refactor

### PR DESCRIPTION
**Pull request by mikewiebe**
Beaker has been refactored in the following ways.

* Renamed cisco vs. netdev root level test directories to better distinguish between the two.
* Moved all test methods out of the UtilityLib module under  cisco-network-puppet-module/tests/beaker_tests/lib/utilitylib.rb so that we can access all beaker/dsl methods within the test methods.  This will enable us to call beaker api's like `fact_on` from within our test methods.

All beaker tests have been run with these changes and are the same as baseline.

```
BASELINE

      Test Suite: tests @ 2015-12-11 05:21:11 -0500

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 4025.25 seconds
      Average Test Time: 28.15 seconds
              Attempted: 143
                 Passed: 132
                 Failed: 4
                Errored: 7
                Skipped: 0
                Pending: 0
                  Total: 143
```

**NOTE** As you can see we have some debugging to do in develop, but these are beyond the scope of this PR.

### CODE REVIEW

**Comment by glennmatthews** [comment]
Look like 4028ea9 reintroduced some "UtilityLib" references - probably needs cleanup?

**Comment by glennmatthews** [comment]
Looks like even after a2b3daf there are a few methods still in the UtilityLib namespace. Is there a reason they couldn't be moved out too?

**Comment by glennmatthews** [comment]
Thanks for doing the file moves in a separate commit from the code changes. :-)

**Comment by mikewiebe** [comment]
@glennmatthews 

* Ack - Cleaning up additional `UtilityLib` references from the merge
* Discussed with @chrisvanheuveln and have now moved the remaining methods/constants outside of the module.  The reason I kept them is there was some issues setting dynamic constants outside a module but I solved this by making the manifest path a non-dynamic constant.  This issue of course being that changes to the manfiest path would break us.

**Comment by mikewiebe** [comment]
@glennmatthews and @chrisvanheuveln I am re-running beaker tests with my latest changes.  Will update as soon as they are done.. about 1 hour to run

**Comment by mikewiebe** [comment]
@glennmatthews @chrisvanheuveln Beaker tests completed.  Still same as baseline.

**Comment by chrisvanheuveln** [comment]
:+1:

**Comment by glennmatthews** [comment]
:+1:

**Pull request merged**
