### PR TITLE
CISCO-74 Fix puppet resource interface defaults

### PR DESCRIPTION
**Pull request by mikewiebe**
Fixes problem where cisco_interface returns illegal default values

Node Utils PR: https://github.com/cisco/cisco-network-node-utils/pull/595

**Tests:**

Puppet Manifest:

```puppet
node default {
  cisco_interface { 'vlan13':
    ensure => present,
  }
}
```

```puppet
[root@guestshell ~]# puppet resource cisco_interface 'vlan13'
cisco_interface { 'vlan13':
  ensure => 'absent',
}
[root@guestshell ~]# 
```

```puppet
[root@guestshell ~]# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for n9k.example.com
Info: Applying configuration version '1536270600'
Notice: /Stage[main]/Main/Node[default]/Cisco_interface[vlan13]/ensure: created
Notice: Applied catalog in 13.29 seconds
[root@guestshell ~]# 
[root@guestshell ~]# puppet resource cisco_interface 'vlan13'
cisco_interface { 'vlan13':
  ensure                                         => 'present',
  access_vlan                                    => '1',
  duplex                                         => 'auto',
  fabric_forwarding_anycast_gateway              => 'false',
  hsrp_bfd                                       => 'false',
  hsrp_delay_minimum                             => '0',
  hsrp_delay_reload                              => '0',
  hsrp_version                                   => '1',
  ipv4_arp_timeout                               => '700',
  ipv4_dhcp_relay_info_trust                     => 'false',
  ipv4_dhcp_relay_subnet_broadcast               => 'false',
  ipv4_dhcp_smart_relay                          => 'false',
  ipv4_forwarding                                => 'false',
  ipv4_pim_sparse_mode                           => 'false',
  ipv4_proxy_arp                                 => 'false',
  ipv4_redirects                                 => 'true',
  ipv6_redirects                                 => 'true',
  load_interval_counter_1_delay                  => '60',
  load_interval_counter_2_delay                  => '300',
  load_interval_counter_3_delay                  => '60',
  mtu                                            => '1500',
  negotiate_auto                                 => 'false',
  pim_bfd                                        => 'false',
  private_vlan_mapping                           => ['108-109'],
  pvlan_mapping                                  => ['108-109'],
  shutdown                                       => 'true',
  speed                                          => 'auto',
  storm_control_broadcast                        => '100.00',
  storm_control_multicast                        => '100.00',
  storm_control_unicast                          => '100.00',
  stp_cost                                       => 'auto',
  stp_link_type                                  => 'auto',
  stp_port_priority                              => '128',
  svi_autostate                                  => 'true',
  svi_management                                 => 'false',
  switchport_autostate_exclude                   => 'false',
  switchport_mode                                => 'disabled',
  switchport_mode_private_vlan_host              => 'disabled',
  switchport_mode_private_vlan_trunk_promiscuous => 'false',
  switchport_mode_private_vlan_trunk_secondary   => 'false',
  switchport_private_vlan_trunk_native_vlan      => '1',
  switchport_pvlan_host                          => 'false',
  switchport_pvlan_promiscuous                   => 'false',
  switchport_pvlan_trunk_allowed_vlan            => 'none',
  switchport_pvlan_trunk_native_vlan             => '1',
  switchport_pvlan_trunk_promiscuous             => 'false',
  switchport_pvlan_trunk_secondary               => 'false',
  switchport_trunk_allowed_vlan                  => '1-4094',
  switchport_trunk_native_vlan                   => '1',
  vpc_peer_link                                  => 'false',
}
[root@guestshell ~]# 
```

Use resource output in manifest:

```puppet
node default {
cisco_interface { 'vlan13':
  ensure                                         => 'present',
  access_vlan                                    => '1',
  duplex                                         => 'auto',
  fabric_forwarding_anycast_gateway              => 'false',
  hsrp_bfd                                       => 'false',
  hsrp_delay_minimum                             => '0',
  hsrp_delay_reload                              => '0',
  hsrp_version                                   => '1',
  ipv4_arp_timeout                               => '700',
  ipv4_dhcp_relay_info_trust                     => 'false',
  ipv4_dhcp_relay_subnet_broadcast               => 'false',
  ipv4_dhcp_smart_relay                          => 'false',
  ipv4_forwarding                                => 'false',
  ipv4_pim_sparse_mode                           => 'false',
  ipv4_proxy_arp                                 => 'false',
  ipv4_redirects                                 => 'true',
  ipv6_redirects                                 => 'true',
  load_interval_counter_1_delay                  => '60',
  load_interval_counter_2_delay                  => '300',
  load_interval_counter_3_delay                  => '60',
  mtu                                            => '1500',
  negotiate_auto                                 => 'false',
  pim_bfd                                        => 'false',
  private_vlan_mapping                           => ['108-109'],
  pvlan_mapping                                  => ['108-109'],
  shutdown                                       => 'true',
  speed                                          => 'auto',
  storm_control_broadcast                        => '100.00',
  storm_control_multicast                        => '100.00',
  storm_control_unicast                          => '100.00',
  stp_cost                                       => 'auto',
  stp_link_type                                  => 'auto',
  stp_port_priority                              => '128',
  svi_autostate                                  => 'true',
  svi_management                                 => 'false',
  switchport_autostate_exclude                   => 'false',
  switchport_mode                                => 'disabled',
  switchport_mode_private_vlan_host              => 'disabled',
  switchport_mode_private_vlan_trunk_promiscuous => 'false',
  switchport_mode_private_vlan_trunk_secondary   => 'false',
  switchport_private_vlan_trunk_native_vlan      => '1',
  switchport_pvlan_host                          => 'false',
  switchport_pvlan_promiscuous                   => 'false',
  switchport_pvlan_trunk_allowed_vlan            => 'none',
  switchport_pvlan_trunk_native_vlan             => '1',
  switchport_pvlan_trunk_promiscuous             => 'false',
  switchport_pvlan_trunk_secondary               => 'false',
  switchport_trunk_allowed_vlan                  => '1-4094',
  switchport_trunk_native_vlan                   => '1',
  vpc_peer_link                                  => 'false',
}
}
```

```puppet
[root@guestshell ~]# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for n9k.example.com
Info: Applying configuration version '1536270834'
Notice: Applied catalog in 12.62 seconds
[root@guestshell ~]# 
```

### CODE REVIEW

**Comment by shermdog** [comment]
Looks like there are still some bad defaults that are contextual.

IOS (vlan)
```
interface Vlan66
  description test
```
Resource output
```Puppet
cisco_interface { 'vlan66':
  ensure                                         => 'present',
  access_vlan                                    => 1,
  description                                    => 'test',
  duplex                                         => 'auto',
  fabric_forwarding_anycast_gateway              => 'false',
  hsrp_bfd                                       => 'false',
  hsrp_delay_minimum                             => 0,
  hsrp_delay_reload                              => 0,
  hsrp_version                                   => 1,
  ipv4_arp_timeout                               => 700,
  ipv4_dhcp_relay_info_trust                     => 'false',
  ipv4_dhcp_relay_subnet_broadcast               => 'false',
  ipv4_dhcp_smart_relay                          => 'false',
  ipv4_forwarding                                => 'false',
  ipv4_pim_sparse_mode                           => 'false',
  ipv4_proxy_arp                                 => 'false',
  ipv4_redirects                                 => 'true',
  ipv6_redirects                                 => 'true',
  load_interval_counter_1_delay                  => 60,
  load_interval_counter_2_delay                  => 300,
  load_interval_counter_3_delay                  => 60,
  mtu                                            => 1500,
  negotiate_auto                                 => 'false',
  pim_bfd                                        => 'false',
  shutdown                                       => 'true',
  speed                                          => 'auto',
  storm_control_broadcast                        => '100.00',
  storm_control_multicast                        => '100.00',
  storm_control_unicast                          => '100.00',
  stp_cost                                       => 'auto',
  stp_link_type                                  => 'auto',
  stp_port_priority                              => 128,
  svi_autostate                                  => 'true',
  svi_management                                 => 'false',
  switchport_autostate_exclude                   => 'false',
  switchport_mode                                => 'disabled',
  switchport_mode_private_vlan_host              => 'disabled',
  switchport_mode_private_vlan_trunk_promiscuous => 'false',
  switchport_mode_private_vlan_trunk_secondary   => 'false',
  switchport_private_vlan_trunk_native_vlan      => 1,
  switchport_pvlan_host                          => 'false',
  switchport_pvlan_promiscuous                   => 'false',
  switchport_pvlan_trunk_allowed_vlan            => 'none',
  switchport_pvlan_trunk_native_vlan             => '1',
  switchport_pvlan_trunk_promiscuous             => 'false',
  switchport_pvlan_trunk_secondary               => 'false',
  switchport_trunk_allowed_vlan                  => '1-4094',
  switchport_trunk_native_vlan                   => 1,
  vpc_peer_link                                  => 'false',
}
```
Apply failure
```
Error: /Stage[main]/Main/Cisco_interface[vlan66]: Could not evaluate: [interface vlan66] The command 'switchport access vlan 1' was rejected with error:
% Invalid command
```


IOS (eth)
```
interface Ethernet1/2
  description test
```

Resource output
```Puppet
cisco_interface { 'ethernet1/2':
  ensure                                         => 'present',
  access_vlan                                    => 1,
  description                                    => 'test',
  duplex                                         => 'auto',
  fabric_forwarding_anycast_gateway              => 'false',
  hsrp_bfd                                       => 'false',
  hsrp_delay_minimum                             => 0,
  hsrp_delay_reload                              => 0,
  hsrp_version                                   => 1,
  ipv4_dhcp_relay_info_trust                     => 'false',
  ipv4_dhcp_relay_subnet_broadcast               => 'false',
  ipv4_dhcp_smart_relay                          => 'false',
  ipv4_forwarding                                => 'false',
  ipv4_pim_sparse_mode                           => 'false',
  ipv4_proxy_arp                                 => 'false',
  ipv4_redirects                                 => 'true',
  ipv6_redirects                                 => 'true',
  load_interval_counter_1_delay                  => 30,
  load_interval_counter_2_delay                  => 300,
  mtu                                            => 1500,
  negotiate_auto                                 => 'true',
  pim_bfd                                        => 'false',
  shutdown                                       => 'false',
  speed                                          => 'auto',
  storm_control_broadcast                        => '100.00',
  storm_control_multicast                        => '100.00',
  storm_control_unicast                          => '100.00',
  stp_cost                                       => 'auto',
  stp_link_type                                  => 'auto',
  stp_port_priority                              => 128,
  switchport_autostate_exclude                   => 'false',
  switchport_mode                                => 'access',
  switchport_mode_private_vlan_host              => 'disabled',
  switchport_mode_private_vlan_trunk_promiscuous => 'false',
  switchport_mode_private_vlan_trunk_secondary   => 'false',
  switchport_private_vlan_trunk_native_vlan      => 1,
  switchport_pvlan_host                          => 'false',
  switchport_pvlan_promiscuous                   => 'false',
  switchport_pvlan_trunk_allowed_vlan            => 'none',
  switchport_pvlan_trunk_native_vlan             => '1',
  switchport_pvlan_trunk_promiscuous             => 'false',
  switchport_pvlan_trunk_secondary               => 'false',
  switchport_trunk_allowed_vlan                  => '1-4094',
  switchport_trunk_native_vlan                   => 1,
  switchport_vtp                                 => 'false',
  vpc_peer_link                                  => 'false',
}
```

Apply failure
```
Error: /Stage[main]/Main/Cisco_interface[ethernet1/2]: Could not evaluate: [interface ethernet1/2] The command 'hsrp delay minimum 0  ' was rejected with error:
ERROR: L2 interface does not support HSRP
```

**Comment by rahushen** [comment]
@shermdog .. just wondering if you have the equivalent node_utils fixes for this issue as well. I'm trying the scenario you highlighted in the comment above and the manifest applies cleanly.

**Comment by shermdog** [comment]
@rahushen confirmed I am using the new code.

Hitting it on N9kv 7.0(3)I7(4)

Bug hits when the vlan interface is non-existent and eth is default

**Comment by saichint** [comment]
@shermdog could you try again? Only node_utils is changed, so please get the latest code from
https://github.com/cisco/cisco-network-node-utils/pull/595

There are no changes on the puppet-module.

**Comment by shermdog** [comment]
@saichint looks like we hit new errors:

```Puppet
cisco_interface { 'vlan66':
  ensure                                         => 'present',
  description                                    => 'test',
  duplex                                         => 'auto',
  fabric_forwarding_anycast_gateway              => 'false',
  hsrp_bfd                                       => 'false',
  hsrp_delay_minimum                             => 0,
  hsrp_delay_reload                              => 0,
  hsrp_version                                   => 1,
  ipv4_arp_timeout                               => 700,
  ipv4_dhcp_relay_info_trust                     => 'false',
  ipv4_dhcp_relay_subnet_broadcast               => 'false',
  ipv4_dhcp_smart_relay                          => 'false',
  ipv4_forwarding                                => 'false',
  ipv4_pim_sparse_mode                           => 'false',
  ipv4_proxy_arp                                 => 'false',
  ipv4_redirects                                 => 'true',
  ipv6_redirects                                 => 'true',
  load_interval_counter_1_delay                  => 60,
  load_interval_counter_2_delay                  => 300,
  load_interval_counter_3_delay                  => 60,
  mtu                                            => 1500,
  negotiate_auto                                 => 'false',
  pim_bfd                                        => 'false',
  shutdown                                       => 'true',
  speed                                          => 'auto',
  storm_control_broadcast                        => '100.00',
  storm_control_multicast                        => '100.00',
  storm_control_unicast                          => '100.00',
  stp_cost                                       => 'auto',
  stp_link_type                                  => 'auto',
  stp_port_priority                              => 128,
  svi_autostate                                  => 'true',
  svi_management                                 => 'false',
  switchport_autostate_exclude                   => 'false',
  switchport_mode                                => 'disabled',
  switchport_mode_private_vlan_host              => 'disabled',
  switchport_mode_private_vlan_trunk_promiscuous => 'false',
  switchport_mode_private_vlan_trunk_secondary   => 'false',
  switchport_private_vlan_trunk_native_vlan      => 1,
  switchport_pvlan_host                          => 'false',
  switchport_pvlan_promiscuous                   => 'false',
  switchport_pvlan_trunk_allowed_vlan            => 'none',
  switchport_pvlan_trunk_native_vlan             => '1',
  switchport_pvlan_trunk_promiscuous             => 'false',
  switchport_pvlan_trunk_secondary               => 'false',
  switchport_trunk_allowed_vlan                  => '1-4094',
  switchport_trunk_native_vlan                   => 1,
  vpc_peer_link                                  => 'false',
}
```
```
Error: /Stage[main]/Main/Cisco_interface[vlan66]: Could not evaluate: [interface vlan66] The command 'speed auto' was rejected with error:
% Invalid command
```

```Puppet
cisco_interface { 'ethernet1/2':
  ensure                                         => 'present',
  access_vlan                                    => 1,
  description                                    => 'test',
  duplex                                         => 'auto',
  fabric_forwarding_anycast_gateway              => 'false',
  hsrp_bfd                                       => 'false',
  ipv4_dhcp_relay_info_trust                     => 'false',
  ipv4_dhcp_relay_subnet_broadcast               => 'false',
  ipv4_dhcp_smart_relay                          => 'false',
  ipv4_forwarding                                => 'false',
  ipv4_pim_sparse_mode                           => 'false',
  ipv4_proxy_arp                                 => 'false',
  ipv4_redirects                                 => 'true',
  ipv6_redirects                                 => 'true',
  load_interval_counter_1_delay                  => 30,
  load_interval_counter_2_delay                  => 300,
  mtu                                            => 1500,
  negotiate_auto                                 => 'true',
  pim_bfd                                        => 'false',
  shutdown                                       => 'false',
  speed                                          => 'auto',
  storm_control_broadcast                        => '100.00',
  storm_control_multicast                        => '100.00',
  storm_control_unicast                          => '100.00',
  stp_cost                                       => 'auto',
  stp_link_type                                  => 'auto',
  stp_port_priority                              => 128,
  switchport_autostate_exclude                   => 'false',
  switchport_mode                                => 'access',
  switchport_mode_private_vlan_host              => 'disabled',
  switchport_mode_private_vlan_trunk_promiscuous => 'false',
  switchport_mode_private_vlan_trunk_secondary   => 'false',
  switchport_private_vlan_trunk_native_vlan      => 1,
  switchport_pvlan_host                          => 'false',
  switchport_pvlan_promiscuous                   => 'false',
  switchport_pvlan_trunk_allowed_vlan            => 'none',
  switchport_pvlan_trunk_native_vlan             => '1',
  switchport_pvlan_trunk_promiscuous             => 'false',
  switchport_pvlan_trunk_secondary               => 'false',
  switchport_trunk_allowed_vlan                  => '1-4094',
  switchport_trunk_native_vlan                   => 1,
  switchport_vtp                                 => 'false',
  vpc_peer_link                                  => 'false',
}
```
```
Error: /Stage[main]/Main/Cisco_interface[ethernet1/2]: Could not evaluate: mtu= cannot be set unless switchport mode is disabled
```

It also looks like loopbacks and port-channels are still affected
```Puppet
cisco_interface { 'loopback66':
  ensure                                         => 'present',
  description                                    => 'test',
  duplex                                         => 'auto',
  fabric_forwarding_anycast_gateway              => 'false',
  hsrp_bfd                                       => 'false',
  hsrp_delay_minimum                             => 0,
  hsrp_delay_reload                              => 0,
  hsrp_version                                   => 1,
  ipv4_dhcp_relay_info_trust                     => 'false',
  ipv4_dhcp_relay_subnet_broadcast               => 'false',
  ipv4_dhcp_smart_relay                          => 'false',
  ipv4_forwarding                                => 'false',
  ipv4_pim_sparse_mode                           => 'false',
  ipv4_proxy_arp                                 => 'false',
  ipv4_redirects                                 => 'false',
  ipv6_redirects                                 => 'true',
  negotiate_auto                                 => 'false',
  pim_bfd                                        => 'false',
  shutdown                                       => 'false',
  speed                                          => 'auto',
  storm_control_broadcast                        => '100.00',
  storm_control_multicast                        => '100.00',
  storm_control_unicast                          => '100.00',
  stp_cost                                       => 'auto',
  stp_link_type                                  => 'auto',
  stp_port_priority                              => 128,
  switchport_autostate_exclude                   => 'false',
  switchport_mode                                => 'disabled',
  switchport_mode_private_vlan_host              => 'disabled',
  switchport_mode_private_vlan_trunk_promiscuous => 'false',
  switchport_mode_private_vlan_trunk_secondary   => 'false',
  switchport_private_vlan_trunk_native_vlan      => 1,
  switchport_pvlan_host                          => 'false',
  switchport_pvlan_promiscuous                   => 'false',
  switchport_pvlan_trunk_allowed_vlan            => 'none',
  switchport_pvlan_trunk_native_vlan             => '1',
  switchport_pvlan_trunk_promiscuous             => 'false',
  switchport_pvlan_trunk_secondary               => 'false',
  switchport_trunk_allowed_vlan                  => '1-4094',
  switchport_trunk_native_vlan                   => 1,
  vpc_peer_link                                  => 'false',
}
```
```
Error: /Stage[main]/Main/Cisco_interface[loopback66]: Could not evaluate: [interface loopback66] The command 'hsrp delay minimum 0  ' was rejected with error:
% Invalid command
```

```Puppet
cisco_interface { 'port-channel5':
  ensure                                         => 'present',
  access_vlan                                    => 1,
  description                                    => 'test',
  duplex                                         => 'auto',
  fabric_forwarding_anycast_gateway              => 'false',
  hsrp_bfd                                       => 'false',
  ipv4_dhcp_relay_info_trust                     => 'false',
  ipv4_dhcp_relay_subnet_broadcast               => 'false',
  ipv4_dhcp_smart_relay                          => 'false',
  ipv4_forwarding                                => 'false',
  ipv4_pim_sparse_mode                           => 'false',
  ipv4_proxy_arp                                 => 'false',
  ipv4_redirects                                 => 'true',
  ipv6_redirects                                 => 'true',
  load_interval_counter_1_delay                  => 30,
  load_interval_counter_2_delay                  => 300,
  mtu                                            => 1500,
  negotiate_auto                                 => 'true',
  pim_bfd                                        => 'false',
  shutdown                                       => 'false',
  speed                                          => 'auto',
  storm_control_broadcast                        => '100.00',
  storm_control_multicast                        => '100.00',
  storm_control_unicast                          => '100.00',
  stp_cost                                       => 'auto',
  stp_link_type                                  => 'auto',
  stp_port_priority                              => 128,
  switchport_autostate_exclude                   => 'false',
  switchport_mode                                => 'access',
  switchport_mode_private_vlan_host              => 'disabled',
  switchport_mode_private_vlan_trunk_promiscuous => 'false',
  switchport_mode_private_vlan_trunk_secondary   => 'false',
  switchport_private_vlan_trunk_native_vlan      => 1,
  switchport_pvlan_host                          => 'false',
  switchport_pvlan_promiscuous                   => 'false',
  switchport_pvlan_trunk_allowed_vlan            => 'none',
  switchport_pvlan_trunk_native_vlan             => '1',
  switchport_pvlan_trunk_promiscuous             => 'false',
  switchport_pvlan_trunk_secondary               => 'false',
  switchport_trunk_allowed_vlan                  => '1-4094',
  switchport_trunk_native_vlan                   => 1,
  switchport_vtp                                 => 'false',
  vpc_peer_link                                  => 'false',
}
```
```
Error: /Stage[main]/Main/Cisco_interface[port-channel5]: Could not evaluate: mtu= cannot be set unless switchport mode is disabled

```

I'd suggest grabbing the resource output of these interface types when only configured w/ a description, deleting the interfaces, and then trying to apply that manifest back.

**Comment by saichint** [comment]
@shermdog Please try again now with latest NU
cisco/cisco-network-node-utils#595

**Comment by shermdog** [comment]
@saichint  So close.

```Puppet
cisco_interface { 'port-channel1':
  ensure                                         => 'present',
  access_vlan                                    => 1,
  description                                    => 'test',
  duplex                                         => 'auto',
  fabric_forwarding_anycast_gateway              => 'false',
  hsrp_bfd                                       => 'false',
  ipv4_forwarding                                => 'false',
  load_interval_counter_1_delay                  => 30,
  load_interval_counter_2_delay                  => 300,
  mtu                                            => 1500,
  negotiate_auto                                 => 'true',
  pim_bfd                                        => 'false',
  shutdown                                       => 'false',
  speed                                          => 'auto',
  storm_control_broadcast                        => '100.00',
  storm_control_multicast                        => '100.00',
  storm_control_unicast                          => '100.00',
  stp_cost                                       => 'auto',
  stp_link_type                                  => 'auto',
  stp_port_priority                              => 128,
  switchport_autostate_exclude                   => 'false',
  switchport_mode                                => 'access',
  switchport_mode_private_vlan_host              => 'disabled',
  switchport_mode_private_vlan_trunk_promiscuous => 'false',
  switchport_mode_private_vlan_trunk_secondary   => 'false',
  switchport_private_vlan_trunk_native_vlan      => 1,
  switchport_pvlan_host                          => 'false',
  switchport_pvlan_promiscuous                   => 'false',
  switchport_pvlan_trunk_allowed_vlan            => 'none',
  switchport_pvlan_trunk_native_vlan             => '1',
  switchport_pvlan_trunk_promiscuous             => 'false',
  switchport_pvlan_trunk_secondary               => 'false',
  switchport_trunk_allowed_vlan                  => '1-4094',
  switchport_trunk_native_vlan                   => 1,
  switchport_vtp                                 => 'false',
  vpc_peer_link                                  => 'false',
}
```
```
Error: /Stage[main]/Main/Cisco_interface[port-channel1]: Could not evaluate: [interface port-channel1] The command 'no vpc peer-link' was rejected with error:
% Invalid command
```

**Comment by saichint** [comment]
@shermdog That is interesting. I am not seeing the same error when running with the latest software on n9k. I don't know if this is related to older versiions. I have not yet done any testing on old releases (I think you are using I4 so I have to downgrade and see if there is any version related issues.

**Comment by saichint** [comment]
@shermdog Confirming that the vpc peer-link CLi is added from I5 code. Also feature vpc need to be enabled. Let me check how to resolve this

**Comment by saichint** [comment]
@shermdog There are limitations on the vpc peer-link based on line card capabilities as well. I don't want to complicate the code by checking individual conditions and make it more hacky. I just added a check to return if the set value is same as get. Can you please try again?

**Comment by shermdog** [comment]
clapping

**Comment by saichint** [comment]
Thank you

**Pull request merged**
