### PR TITLE
Create NOTICE

### PR DESCRIPTION
**Pull request by eckelcu**

### CODE REVIEW

**Comment by mikewiebe** [comment]
@eckelcu Hi Charles.  We already added a `NOTICE` file a few days ago.  See the following.

https://github.com/cisco/cisco-network-puppet-module/blob/develop/NOTICE

**Comment by eckelcu** [comment]
Thanks for adding the NOTICE file. It would be best if you added the project name as the first line of the NOTICE file to clarify what the copyright statement covers. This will become more important if/when you add attribution for any dependencies in this NOTICE file.

**Comment by mikewiebe** [comment]
@eckelcu Done.

https://github.com/cisco/cisco-network-puppet-module/blob/develop/NOTICE

I am going to close this PR now.

**Comment by eckelcu** [comment]
Great, Mike. Thanks for adding.

Cheers,
Charles

**Pull request closed without merging**
