### PR TITLE
implementing speed and duplex with tests

### PR DESCRIPTION
**Pull request by tphoney**
this is waiting on https://github.com/cisco/cisco-network-node-utils/pull/47/files

### CODE REVIEW

**Comment by chrisvanheuveln** [comment]
Your changes look fine but please include beaker test results with your PRs. I'll merge after that. Thanks.

**Comment by mikewiebe** [comment]
@tphoney Can you also add these to the demo manifest under https://github.com/cisco/cisco-network-puppet-module/blob/develop/examples/demo_interface.pp.

**Comment by chrisvanheuveln** [comment]
...aaaand the CHANGELOG file too. I always forget that one.

**Comment by tphoney** [comment]
TestCase :: ROUTEDINTF Resource :: All Attributes Defaults :: PASS
  TestCase :: ROUTEDINTF Resource :: All Attributes Defaults :: PASS
TestCase :: ROUTEDINTF Resource :: All Attributes Defaults :: End
tests/beaker_tests/routedintf/routedintf_provider_defaults.rb passed in 53.41 seconds
      Test Suite: tests @ 2015-11-03 14:28:27 +0000

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 53.41 seconds
      Average Test Time: 53.41 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -

Failed Tests Cases:
Errored Tests Cases:
Skipped Tests Cases:
Pending Tests Cases:

**Comment by tphoney** [comment]
tests/beaker_tests/routedintf/routedintf_provider_nondefaults.rb passed in 68.95 seconds
      Test Suite: tests @ 2015-11-03 14:34:41 +0000

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 68.95 seconds
      Average Test Time: 68.95 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -

Failed Tests Cases:
Errored Tests Cases:
Skipped Tests Cases:
Pending Tests Cases:

No tests to run for suite 'post_suite'
Cleanup: cleaning up after successful run

**Comment by tphoney** [comment]
@chrisvanheuveln @mikewiebe all the changes have been implemented.

**Comment by tphoney** [comment]
@chrisvanheuveln @mikewiebe all the changes have been implemented.

**Pull request merged**
