### PR TITLE
grpc_port parameter supported in hosts cfg file

### PR DESCRIPTION
**Pull request by robert-w-gries**
Adds support for grpc_port parameter in hosts.cfg file and allows connection to grpc port on switch.

### CODE REVIEW

**Comment by glennmatthews** [comment]
Does this (especially the removal of 'sudo') break nexus?

**Comment by robert-w-gries** [comment]
Yes it does. Should I implement nexus support and open a new PR against develop?

**Comment by glennmatthews** [comment]
Still should go into feature/grpc for now, but we do want it to work on nexus.

I think you can keep nexus compatibility by just checking whether grpc_port is set and branching appropriately.

**Comment by glennmatthews** [comment]
Something like:

```
     when /cisco/
       agentvrf = options[:HOSTS][host.to_s.to_sym]['vrf']
+      grpc_port = options[:HOSTS][host.to_s.to_sym]['grpc_port']
+      if grpc_port.nil?
          return "sudo ip netns exec #{agentvrf} " + cmdstr
+      else
+        node_var = "export NODE=\"127.0.0.1:#{grpc_port} root lab\""
+        return "#{node_var} && ip netns exec #{agentvrf} " + cmdstr
+      end
```

**Comment by robert-w-gries** [comment]
Is there a way to check that the platform is `ios_xr` instead?  Checking `grpc_port.nil?` would fail if using grpc UDS.

**Comment by glennmatthews** [comment]
When we have a UDS, you won't need to set grpc_port. 

This will need to be reworked anyway if/when we have a final design in place from gRPC team.

**Comment by robert-w-gries** [comment]
I meant that this command would fail `return "sudo ip netns exec #{agentvrf} " + cmdstr` since sudo doesn't work right now.  But that bug would probably be fixed before UDS is implemented anyway

I'm going with your suggested change.

**Comment by robert-w-gries** [comment]
Beaker now runs for both nexus and XR

**Comment by robert-w-gries** [comment]
Updated documentation and added comment

**Pull request merged**
