### PR TITLE
README updates to add support on ios_xr for ntp_config and syslog_server

### PR DESCRIPTION
**Pull request by jonnytpuppet**

### CODE REVIEW

**Comment by glennmatthews** [comment]
Beaker tests pass as-is for these providers?

**Comment by jonnytpuppet** [comment]
@glennmatthews Yup, they do indeed

**Comment by glennmatthews** [comment]
Would be nice to provide Beaker test results against NX and XR in this PR to demonstrate it - but :+1: in any case. :-)

**Comment by jonnytpuppet** [comment]
XR results:


```
ests/beaker_tests/ntp_config/ntp_config_provider_defaults.rb passed in 48.20 seconds
      Test Suite: tests @ 2016-03-14 15:04:38 +0000

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 48.20 seconds
      Average Test Time: 48.20 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -

Failed Tests Cases:
Errored Tests Cases:
Skipped Tests Cases:
Pending Tests Cases:
```

```
tests/beaker_tests/syslog_server/syslog_server_provider_defaults.rb passed in 74.88 seconds
      Test Suite: tests @ 2016-03-14 15:09:22 +0000

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 74.89 seconds
      Average Test Time: 74.89 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -

Failed Tests Cases:
Errored Tests Cases:
Skipped Tests Cases:
Pending Tests Cases:

No tests to run for suite 'post_suite'
Cleanup: cleaning up after successful run
```

```
tests/beaker_tests/netdev_stdlib/name_server_provider_defaults.rb passed in 44.94 seconds
      Test Suite: tests @ 2016-03-14 15:11:01 +0000

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 44.94 seconds
      Average Test Time: 44.94 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -

Failed Tests Cases:
Errored Tests Cases:
Skipped Tests Cases:
Pending Tests Cases:

No tests to run for suite 'post_suite'
Cleanup: cleaning up after successful run
```

**Comment by robert-w-gries** [comment]
:+1:

**Comment by robert-w-gries** [comment]
There are merge conflicts right now.  Please merge in latest develop into your working branch and push.

**Comment by jonnytpuppet** [comment]
@robert-w-gries @glennmatthews @mikewiebe Code updated to resolve conflicts

**Pull request merged**
