### PR TITLE
Added IOS XR support for snmp_user

### PR DESCRIPTION
**Pull request by jonnytdevops**
This is to bring IOS XR support to snmp_user
This provider does not supported unencrypted passwords, thus all password specified must be already encrypted.

```
tests/beaker_tests/snmp_user/snmp_user_provider_defaults.rb passed in 234.26 seconds
      Test Suite: tests @ 2016-06-14 18:04:38 +0100

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 234.28 seconds
      Average Test Time: 234.28 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -
```

### CODE REVIEW

**Comment by jonnytdevops** [comment]
Needs https://github.com/puppetlabs/netdev_stdlib/pull/20 for v2c support

**Comment by chburket** [comment]
:+1:

**Comment by mikewiebe** [comment]
@jonnytdevops Do you have nexus results?

**Comment by jonnytdevops** [comment]
@mikewiebe I don't have a nexus environment set up at present, however I can work on that. In the mean time, do you have any additional code feedback?

Thanks 

JT

**Comment by mikewiebe** [comment]
@jonnytdevops No additional comments on the code, but want to be certain that the changes don't break Nexus.

**Pull request merged**
