### PR TITLE
network_snmp ios_xr does not support global enable

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
@mikewiebe @chburket i am experiencing a weird test failure with my VM in a VM in a VM. What could go wrong :P 

This should pass, and has passed manually. But not in test. Could you look ?

**Comment by tphoney** [comment]
@mikewiebe @chburket i need you guys to look at this, it should pass. but i get the following:
n9kv1 15:33:16$ source /etc/profile; sudo sh -c " ip netns exec management /opt/puppetlabs/bin/puppet resource network_snmp default "
      network_snmp { 'default':
        contact  => 'unset',
        enable   => 'false',
        location => 'unset',
      }

    n9kv1 executed in 2.21 seconds

    n9kv1 15:33:18$ source /etc/profile; sudo sh -c " ip netns exec management /opt/puppetlabs/bin/facter os.name "
      nexus

    n9kv1 executed in 0.17 seconds
    Warning:
    TestStep :: Match (?-mix:enable +=> +'?false'?) :: FAIL


apparently false != false

**Comment by mikewiebe** [comment]
@tphoney I ran the test on my n9k and it passes:
```
Begin network_snmp/network_snmp_provider_defaults.rb

TestCase :: network_snmp Resource :: All Attributes Defaults
  
  * TestStep :: Setup switch for provider
    Setup switch for provider
  
  * TestStep :: Get resource set manifest from master
    Get resource set manifest from master :: PASS
  
  * TestStep :: Check network_snmp resource presence on agent
    Check network_snmp resource presence on agent :: PASS
  
  * TestStep :: Get resource unset manifest from master
    Get resource unset manifest from master :: PASS
  
  * TestStep :: Check network_snmp resource presence on agent
    Check network_snmp resource presence on agent :: PASS
  
  
  TestCase :: network_snmp Resource :: All Attributes Defaults :: PASS
  TestCase :: network_snmp Resource :: All Attributes Defaults :: PASS
TestCase :: network_snmp Resource :: All Attributes Defaults :: End
Begin teardown
End teardown
network_snmp/network_snmp_provider_defaults.rb passed in 41.78 seconds
      Test Suite: tests @ 2016-06-09 00:51:24 -0400

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 41.78 seconds
      Average Test Time: 41.78 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -
```
Not sure what is happening in your case, but this looks ok to me 👍

**Comment by tphoney** [comment]
@mikewiebe @chburket can i get a merge :)

**Comment by mikewiebe** [comment]
Waiting for a 👍 from @chburket

**Pull request merged**
