### PR TITLE
Collapse Release 1.1.0 into master

### PR DESCRIPTION
**Pull request by mikewiebe**

### CODE REVIEW

**Comment by mikewiebe** [comment]
@hunner , @jonnytpuppet , @HelenCampbell , @bmjen  Please comment on this release PR.  The goal is to collapse by Wed next week if possible.  Thanks!

**Comment by hunner** [comment]
netdev_stdlib 0.11.0 is out with the changes incorporated in this release. In addition, I had a few other small metadata.json tweaks:
~~~diff
 metadata.json | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
diff --git a/metadata.json b/metadata.json
index 5af9efc..1049a80 100644
--- a/metadata.json
+++ b/metadata.json
@@ -8,16 +8,16 @@
   "project_page": "https://github.com/cisco/cisco-network-puppet-module",
   "issues_url": "https://github.com/cisco/cisco-network-puppet-module/issues",
   "dependencies": [
-    { "name": "puppetlabs/netdev_stdlib", "version_requirement": ">=0.10.0" }
+    {"name":"puppetlabs/netdev_stdlib","version_requirement":">=0.11.0"}
   ],
   "requirements": [
     {
       "name": "pe",
-      "version_requirement": "~> 2015.2"
+      "version_requirement": "2015.2.x"
     },
     {
       "name": "puppet",
-      "version_requirement": "~> 4.0"
+      "version_requirement": "4.x"
     }
   ],
   "tags": [
~~~

**Comment by hunner** [comment]
When reviewing `cisco_vrf`, `cisco_bgp`, `cisco_bgp_af`, `cisco_bgp_neighbor`, and `cisco_bgp_neighbor_af` types and providers I had the following minor notes:

- Lots of the cisco_bgp_af type's properties are doing validation in the munge block. This may be on purpose due to the `'default'` to `:default` casting.
- The cisco_bgp_neighbor and cisco_bgp_neighbor_af global validate block (at the end) checks `self[:asn].nil?` (and other values); I believe `self[:whatever]` values will be nil during `puppet resource cisco_bgp_neighbor` commands and will throw an error from `self.instances`
- The cisco_bgp_neighbor_af global validate block is on line 243, but is traditionally at the end after all properties and before autorequires, if any. I would recommend moving it down.
- For the cisco_bgp_af provider, the networks getter calls `@resource[:networks][0]` which on puppet 3.x would fail for single-element values as puppet 3 and lower cast single-element array values to the value itself; metadata.json says that this module only supports puppet 4 so this is fine, though something to be aware of if it will ever be compatible with puppet 3.
- Otherwise for the providers, it is all the standard meta-programming wrapping around the utils class. Historically puppet providers have been glorified shell scripts, but regular APIs are being wrapped more and more often. It would be great if puppet types and providers could be generated in this fashion from API definitions in the future, but no recommendation at this time.

**Comment by mikewiebe** [comment]
@hunner Responses to your comments:

- Lots of the cisco_bgp_af type's properties are doing validation in the munge block. This may be on purpose due to the `'default'` to `:default` casting.
  - (@mikewiebe) That is correct.  We can revisit this if needed post release 1.1.0.

- The cisco_bgp_neighbor and cisco_bgp_neighbor_af global validate block (at the end) checks `self[:asn].nil?` (and other values); I believe `self[:whatever]` values will be nil during `puppet resource cisco_bgp_neighbor` commands and will throw an error from `self.instances`
  - (@mikewiebe) Here are a couple examples using the `puppet resource cisco_bgp_neighbor` command with and without bgp neighbors configured.  I believe it is working as expected.

**BGP not configured**
```
dt-n9k5-1(config)# sh run | include bgp
dt-n9k5-1(config)# 
```

```
root@dt-n9k5-1#puppet resource cisco_bgp_neighbor
root@dt-n9k5-1#
```

**BGP neighbors configured**
```
dt-n9k5-1# sh run bgp

!Command: show running-config bgp
!Time: Mon Nov  9 16:15:05 2015

version 7.0(3)I2(2)
feature bgp

router bgp 55
  neighbor 6::6
  neighbor 5.5.5.5
  vrf green
    neighbor 6::6
    neighbor 5.5.5.5


dt-n9k5-1# 
```

```
root@dt-n9k5-1#puppet resource cisco_bgp_neighbor
cisco_bgp_neighbor { '55 default 5.5.5.5':
  ensure                 => 'present',
  capability_negotiation => 'true',
  connected_check        => 'true',
  dynamic_capability     => 'true',
  ebgp_multihop          => 'false',
  local_as               => '0',
  log_neighbor_changes   => 'inherit',
  low_memory_exempt      => 'false',
  maximum_peers          => '0',
  remote_as              => '0',
  remove_private_as      => 'disable',
  shutdown               => 'false',
  suppress_4_byte_as     => 'false',
  timers_holdtime        => '180',
  timers_keepalive       => '60',
  transport_passive_only => 'false',
}
cisco_bgp_neighbor { '55 default 6::6':
  ensure                 => 'present',
  capability_negotiation => 'true',
  connected_check        => 'true',
  dynamic_capability     => 'true',
  ebgp_multihop          => 'false',
  local_as               => '0',
  log_neighbor_changes   => 'inherit',
  low_memory_exempt      => 'false',
  maximum_peers          => '0',
  remote_as              => '0',
  remove_private_as      => 'disable',
  shutdown               => 'false',
  suppress_4_byte_as     => 'false',
  timers_holdtime        => '180',
  timers_keepalive       => '60',
  transport_passive_only => 'false',
}
cisco_bgp_neighbor { '55 green 5.5.5.5':
  ensure                 => 'present',
  capability_negotiation => 'true',
  connected_check        => 'true',
  dynamic_capability     => 'true',
  ebgp_multihop          => 'false',
  local_as               => '0',
  log_neighbor_changes   => 'inherit',
  low_memory_exempt      => 'false',
  maximum_peers          => '0',
  remote_as              => '0',
  remove_private_as      => 'disable',
  shutdown               => 'false',
  suppress_4_byte_as     => 'false',
  timers_holdtime        => '180',
  timers_keepalive       => '60',
  transport_passive_only => 'false',
}
cisco_bgp_neighbor { '55 green 6::6':
  ensure                 => 'present',
  capability_negotiation => 'true',
  connected_check        => 'true',
  dynamic_capability     => 'true',
  ebgp_multihop          => 'false',
  local_as               => '0',
  log_neighbor_changes   => 'inherit',
  low_memory_exempt      => 'false',
  maximum_peers          => '0',
  remote_as              => '0',
  remove_private_as      => 'disable',
  shutdown               => 'false',
  suppress_4_byte_as     => 'false',
  timers_holdtime        => '180',
  timers_keepalive       => '60',
  transport_passive_only => 'false',
}
root@dt-n9k5-1#
```

- The cisco_bgp_neighbor_af global validate block is on line 243, but is traditionally at the end after all properties and before autorequires, if any. I would recommend moving it down.
  - (@mikewiebe) Good catch, will move it down.

- For the cisco_bgp_af provider, the networks getter calls `@resource[:networks][0]` which on puppet 3.x would fail for single-element values as puppet 3 and lower cast single-element array values to the value itself; metadata.json says that this module only supports puppet 4 so this is fine, though something to be aware of if it will ever be compatible with puppet 3.
  - (@mikewiebe) Thanks for the heads up.


- Otherwise for the providers, it is all the standard meta-programming wrapping around the utils class. Historically puppet providers have been glorified shell scripts, but regular APIs are being wrapped more and more often. It would be great if puppet types and providers could be generated in this fashion from API definitions in the future, but no recommendation at this time.
  - (@mikewiebe) Agreed, that would be a worthwhile enhancement.

**Comment by mikewiebe** [comment]
@hunner Regarding the following comment.

netdev_stdlib 0.11.0 is out with the changes incorporated in this release. In addition, I had a few other small metadata.json tweaks:

Good catch and thanks for the suggested tweaks.

**Comment by hunner** [comment]
:+1:

**Comment by hunner** [comment]
@mikewiebe Actually found something else; you have `~> 4.x` and `~> 2015.2.x`  in the puppet & PE versions in the metadata.json, but they should be just `4.x` and `2015.2.x` respectively (ie, no `~>`).

**Comment by mikewiebe** [comment]
@hunner Thanks for checking that !  Fixed.

**Pull request merged**
