### PR TITLE
Release 2.0.0 Fixes

### PR DESCRIPTION
**Pull request by mikewiebe**
As highlighted by utilitylib fix

### CODE REVIEW

**Comment by Thomas-Franklin** [comment]
Ah the stderrs are on different lines so it took both

**Comment by willmeek** [comment]
It looks like my rebase brought down the existing stderr then added mine (I was kinda expecting a conflict that never occurred)

**Comment by mikewiebe** [comment]
@Thomas-Franklin Should be fixed now.. Just waiting for Travis to complete

**Comment by willmeek** [comment]
Travis says yes

**Pull request merged**
